// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddGender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGender));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091014176_AddGender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
