// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMessages));
        
        string IMigrationMetadata.Id
        {
            get { return "202004101748042_AddMessages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
