//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSubCategory
    {
        public int Id { get; set; }
        public Nullable<int> MainCategoryId { get; set; }
        public string SubCategoryNameArabic { get; set; }
        public string SubCategoryNameEnglish { get; set; }
        public Nullable<int> Calories { get; set; }
    
        public virtual FoodMainCategories FoodMainCategories { get; set; }
    }
}
