//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthyLineeEntities : DbContext
    {
        public HealthyLineeEntities()
            : base("name=HealthyLineeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Diseases> Diseases { get; set; }
        public virtual DbSet<FoodMainCategories> FoodMainCategories { get; set; }
        public virtual DbSet<FoodSubCategory> FoodSubCategory { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<RecipesIngredients> RecipesIngredients { get; set; }
        public virtual DbSet<RecipesSteps> RecipesSteps { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserDiseases> UserDiseases { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    }
}
